### ISSUE TITLE
Exploratory Data Analysis

### ISSUE THREAD

**Issue by Uthmanic** [HamoyeHQ/stage-f-01-road-safety#5]
Explore the data using visualizations to gain valid insights and answer questions like:

1. What is the severity of accidents over the last decade?
2. When do accidents usually happen?
3. Where do cyclists accidents usually happen?
4. Under which circumstances do accidents happen? Is there any correlation between these features?
5. What is the age distribution of drivers involved in the accidents?
6. What are the characteristics of casualties impacted in the accidents?
7. What are the main factors causing an accidents, and can we predict the severity based on these factors?

**Comment by alextoyese** [comment]
Acknowledge receipt of your email

**Comment by Aanuadu** [comment]
Mail well received
